# Generated by Django 4.2.10 on 2024-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofilemodel",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
