# Generated by Django 4.2.10 on 2024-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_full_name_userprofilemodel_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofilemodel",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofilemodel",
            name="last_name",
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
