# Generated by Django 4.2.10 on 2024-02-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_foodmodel_recipemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemodel",
            name="instructions",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="recipemodel",
            name="picture",
            field=models.ImageField(default="", upload_to="food_picture/"),
        ),
    ]
