# Generated by Django 4.2.10 on 2024-02-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_recipemodel_instructions_alter_recipemodel_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemodel",
            name="ingredients",
            field=models.TextField(default=""),
        ),
    ]
