# Generated by Django 4.2.10 on 2024-02-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_userprofilemodel_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilemodel",
            name="valid_till",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
