# Generated by Django 4.2.10 on 2024-02-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_userprofilemodel_valid_till"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemodel",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
